# Generated by Django 2.2.2 on 2019-06-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('age', models.IntegerField(verbose_name='How old is he/her?')),
            ],
        ),
    ]
